# Use the official MongoDB image as the base image
FROM mongo:latest

# Set environment variables for MongoDB configuration
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=admin
ENV MONGO_INITDB_DATABASE=mydatabase

# Copy a custom configuration file (if needed)
# COPY mongodb.conf /etc/mongo/mongodb.conf

# Expose the default MongoDB port (27017)
EXPOSE 27017

# Start MongoDB when the container launches
CMD ["mongod"]
