awsConfigSecret:
  config: "xxxyy"
awsCredentialsSecret:
  credentials: "yyyxx"
kubernetesClusterDomain: cluster.local
tenantOperationsController:
  replicas: 1
  toc:
    image:
      repository: radhakrishna0018/deployer
      tag: 0.0.11
tenantOperationsControllerWeb:
  replicas: 1
  tocWeb:
    image:
      repository: radhakrishna0018/deployer-web
      tag: "5.2"
toc:
  ports:
  - name: toc-svc
    port: 7000
    protocol: TCP
    targetPort: 7000
  type: ClusterIP
tocWeb:
  ports:
  - name: toc-web-svc
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
