apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toc.fullname" . }}-aws-config-secret
  labels:
  {{- include "toc.labels" . | nindent 4 }}
stringData:
  config: {{ required "awsConfigSecret.config is required" .Values.awsConfigSecret.config
    | quote }}