apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toc.fullname" . }}-aws-credentials-secret
  labels:
  {{- include "toc.labels" . | nindent 4 }}
stringData:
  credentials: {{ required "awsCredentialsSecret.credentials is required" .Values.awsCredentialsSecret.credentials
    | quote }}