apiVersion: v1
kind: Service
metadata:
  name: {{ include "toc.fullname" . }}-toc-web
  labels:
  {{- include "toc.labels" . | nindent 4 }}
  annotations:
    autoheal: "true"
    metallb.universe.tf/allow-shared-ip: key-to-share-1.2.3.4
spec:
  type: {{ .Values.tocWeb.type }}
  selector:
    app: toc-web
  {{- include "toc.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.tocWeb.ports | toYaml | nindent 2 -}}