apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "toc.fullname" . }}-toc-role-binding
  labels:
  {{- include "toc.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: '{{ include "toc.fullname" . }}-toc-sa'
  namespace: '{{ .Release.Namespace }}'