---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials-secret
stringData:
  credentials: |
    [default]
    aws_access_key_id = 
    aws_secret_access_key = 
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-config-secret
stringData:
  config: |
    [default]
    output = json
    region = us-east-1